# Krono growth dashboard — the C-Check step of the PDCA loop.
# Snapshots stars/forks/watchers for Krono + a competitor watchlist via the
# GitHub API, appends to dashboard/history.csv (time series), renders
# dashboard/DASHBOARD.md, and prints a summary. Run daily.
#
#   powershell -NoProfile -ExecutionPolicy RemoteSigned -File tools/dashboard.ps1

$ErrorActionPreference = 'Continue'

# --- config -----------------------------------------------------------------
$kronoRepo   = 'krono-sh/krono'   # update to the real slug once the repo is pushed
$competitors = @(
  'n8n-io/n8n', 'louislam/uptime-kuma', 'apache/airflow', 'kestra-io/kestra',
  'windmill-labs/windmill', 'triggerdotdev/trigger.dev', 'hatchet-dev/hatchet',
  'inngest/inngest', 'go-co-op/gocron', 'robfig/cron'
)
$redLineDailyAvg = 5   # 7-day rolling star avg below this = stagnation red-line

# --- paths ------------------------------------------------------------------
$root   = Split-Path -Parent $PSScriptRoot
$outDir = Join-Path $root 'dashboard'
New-Item -ItemType Directory -Force -Path $outDir | Out-Null
$histCsv = Join-Path $outDir 'history.csv'
$mdFile  = Join-Path $outDir 'DASHBOARD.md'
$today   = Get-Date -Format 'yyyy-MM-dd'

# --- fetch ------------------------------------------------------------------
function Get-RepoStats {
  param([string]$Slug)
  $raw = gh api "repos/$Slug" --jq '{s:.stargazers_count,f:.forks_count,w:.subscribers_count}' 2>$null
  if (-not $raw) { return $null }
  try { return ($raw | ConvertFrom-Json) } catch { return $null }
}

if (-not (Test-Path $histCsv)) {
  Set-Content -Path $histCsv -Value 'date,repo,stars,forks,watchers' -Encoding ascii
}

$snapshot = @()
foreach ($slug in (@($kronoRepo) + $competitors)) {
  $st = Get-RepoStats -Slug $slug
  if ($st) { $s = [int]$st.s; $f = [int]$st.f; $w = [int]$st.w; $live = $true }
  else     { $s = 0;          $f = 0;          $w = 0;          $live = $false }
  Add-Content -Path $histCsv -Value "$today,$slug,$s,$f,$w" -Encoding ascii
  $snapshot += [pscustomobject]@{ repo = $slug; stars = $s; forks = $f; watchers = $w; live = $live }
}

# --- deltas -----------------------------------------------------------------
$hist = Import-Csv $histCsv
function Get-StarDelta {
  param([string]$Slug)
  $series = @($hist | Where-Object { $_.repo -eq $Slug } | Sort-Object date)
  if ($series.Count -lt 2) { return $null }
  return [int]$series[-1].stars - [int]$series[-2].stars
}
function Get-7dAvg {
  param([string]$Slug)
  $series = @($hist | Where-Object { $_.repo -eq $Slug } | Sort-Object date)
  if ($series.Count -lt 2) { return $null }
  $window = [math]::Min(7, $series.Count - 1)
  $delta  = [int]$series[-1].stars - [int]$series[-1 - $window].stars
  return [math]::Round($delta / $window, 1)
}
function Fmt($v) { if ($null -eq $v) { '-' } else { "$v" } }

# --- render -----------------------------------------------------------------
$k       = $snapshot[0]
$kDelta  = Get-StarDelta -Slug $kronoRepo
$kAvg    = Get-7dAvg     -Slug $kronoRepo
$redLine = if (($null -ne $kAvg) -and ($kAvg -lt $redLineDailyAvg)) { 'TRIPPED -> trigger A-Act' } else { 'ok' }

$md = New-Object System.Collections.Generic.List[string]
$md.Add("# Krono Growth Dashboard - $today")
$md.Add("")
$md.Add("## Krono  (``$kronoRepo``)")
if ($k.live) {
  $md.Add("- Stars **$($k.stars)**  (1d change $(Fmt $kDelta))   Forks $($k.forks)   Watchers $($k.watchers)")
  $md.Add("- 7-day star avg: **$(Fmt $kAvg)/day**  - red-line < $redLineDailyAvg/day -> **$redLine**")
} else {
  $md.Add("- Not yet on GitHub (repo not pushed). Tracking starts the day it goes public.")
}
$md.Add("")
$md.Add("## Competitor watchlist")
$md.Add("")
$md.Add("| Repo | Stars | 1d change | Forks | Watchers |")
$md.Add("|---|--:|--:|--:|--:|")
foreach ($r in $snapshot[1..($snapshot.Count - 1)]) {
  $md.Add("| $($r.repo) | $($r.stars) | $(Fmt (Get-StarDelta -Slug $r.repo)) | $($r.forks) | $($r.watchers) |")
}
$md.Add("")
$md.Add("_Snapshot appended to ``dashboard/history.csv``. Generated by ``tools/dashboard.ps1``._")
Set-Content -Path $mdFile -Value ($md -join "`r`n") -Encoding utf8

# --- console summary --------------------------------------------------------
Write-Host ""
Write-Host "Krono dashboard - $today" -ForegroundColor Cyan
if ($k.live) {
  Write-Host ("  Krono: {0} stars (1d {1}), 7d avg {2}/day [{3}]" -f $k.stars, (Fmt $kDelta), (Fmt $kAvg), $redLine)
} else {
  Write-Host "  Krono: not yet pushed to GitHub (0 stars) - tracking begins at launch"
}
Write-Host ("  Competitors snapshotted: {0}" -f $competitors.Count)
Write-Host ("  Board:   {0}" -f $mdFile)
Write-Host ("  History: {0}" -f $histCsv)
Write-Host ""
